blank_issues_enabled: false
contact_links:
  - name: Read the Community Guidelines
    about: "Please make sure you have read the submission guidelines before posting an issue"
    url: https://github.com/trafilea/nx-shopify/blob/master/CONTRIBUTING.md#-submitting-an-issue
  - name: Is you issue Nx related?
    about: "If you issue is not related with this plugin but rather related with Nx itself, please go to the Nx project and report it there."
    url: https://github.com/nrwl/nx
